### ISSUE TITLE
Makefile:117: recipe for target 'dmdb' failed

### ISSUE THREAD

**Issue by cinocinelli** [youngsamwei/DongmenDB#11]
![image](https://user-images.githubusercontent.com/44538009/64862151-602ac480-d664-11e9-8029-de204c955cb5.png)
编译出错
已经尝试过换不同版本的Clion 和 Mingw 但是没有效果 
求教 thx

**Comment by FancyKings** [comment]
你好，我这里说一下我个人的建议，供您参考
+ 从我这里来看，图中所示的报错文件在已经编译运行成功的电脑上，依然是有相同报错的，所以大概可以推断该报错并不直接影响代码`Target`的运行成功，可能是由于其他依赖项或者运行条件不满足导致的
![ERROR](http://img.vim-cn.com/dd/1aada07a27dcd497dda99fcbd050cea3a83923.png)
+ 请检查`Makefile`与`Makefile2`等`CMake`相关文件未经改动且本地`CMake`满足最低要求
![Make](https://img.vim-cn.com/68/70601eb5ab831c5001e157047947857e04717e.png)
+ 如果你没有改动仓库的任何代码出现图中所示情况，你可以先将你的仓库更新到最新版本，同步到本地后解决冲突再次尝试编译，假如再次出现问题，你可以更换环境为[视频简介中所示](https://www.bilibili.com/video/av66411568/)，或者比对差异，尝试问题是否解决
+ 如果依然无效，或者你在本地改动了仓库的部分代码或结构，则可以尝试先将改动代码恢复或注释的方法尝试问题是否解决，如果可以，可以尝试`Debug`模式(没跑起来估计不行)
+ 如果还不行……俺这个小白也不知道了，那你可以尝试线下找一个成功的对比着来或者提供更具体的信息，我这边的Tool Chain配置为
![ToolChain](http://img.vim-cn.com/d6/bcd72da48d6f82738c4cbdd7887ef3143e18ea.png)
+ 终极大法，@老师


***上述视频由于录制时未考虑后续更新的问题，并未采用 `git clone` 的方式，建议将代码下载到本地时使用git进行同步***
中秋节快乐，皮一下下加一个Label
![Yeah](https://github.com/getActivity/EmojiPackage/blob/master/%E5%92%B8%E9%B1%BC/%E6%91%B8%E7%9D%80%E6%88%91%E5%8F%AF%E7%88%B1%E7%9A%84%E8%87%AA%E5%B7%B1.gif?raw=true)

**Comment by cinocinelli** [comment]
感谢回复 
我尝试了最新版的mingw 8.1.0 使之有效了
