### ISSUE TITLE
运行不了这是怎么回事

### ISSUE THREAD

**Issue by ouxiaobai** [youngsamwei/DongmenDB#12]
mingw32-make.exe[3]: *** [googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.obj] Error 1
mingw32-make.exe[2]: *** [googletest/CMakeFiles/gtest.dir/all] Error 2
CMakeFiles\Makefile2:789: recipe for target 'src_experiment/exp_05_algebra_opt/CMakeFiles/Exp_05_02_ConditionPushdownTest.dir/rule' failed
mingw32-make.exe[1]: *** [src_experiment/exp_05_algebra_opt/CMakeFiles/Exp_05_02_ConditionPushdownTest.dir/rule] Error 2
mingw32-make.exe: *** [Exp_05_02_ConditionPushdownTest] Error 2
Makefile:299: recipe for target 'Exp_05_02_ConditionPushdownTest' failed

**Comment by youngsamwei** [comment]
一般是配置问题，
首先检查mingw的版本和cmake的版本
