### ISSUE TITLE
测评系统编译出错  http://192.168.130.197:8080

### ISSUE THREAD

**Issue by cinocinelli** [youngsamwei/DongmenDB#17]
![image](https://user-images.githubusercontent.com/44538009/66194356-dbf9b900-e6c6-11e9-8de4-d0195e0de12f.png)

**Comment by FancyKings** [comment]
确实坏了哎，我交原来过了的也不好使，等老师修吧~
@youngsamwei

**Comment by youngsamwei** [comment]
先确保在自己机器上成功执行测试用例

**Comment by youngsamwei** [comment]
已经重启测评系统，请再登录测试
