### ISSUE TITLE
这又是啥

### ISSUE THREAD

**Issue by ouxiaobai** [youngsamwei/DongmenDB#19]
D:\databases\DongmenDB-master\bin\exp_01_04_update_test.exe --gtest_color=no
com.jetbrains.cidr.execution.debugger.backend.gdb.GDBDriver$GDBCommandException: Error creating process D:\databases\DongmenDB-master\bin\exp_01_04_update_test.exe, (error 740).

**Comment by youngsamwei** [comment]
应该是在服务器端执行此测试的进程太多了，exp_01_04_update_test.exe貌似进入死循环，无法结束
