### ISSUE TITLE
测评网站实验3的后台sql语句可能有误

### ISSUE THREAD

**Issue by sunmaoxiang** [youngsamwei/DongmenDB#20]
《实验3 Delete语句解析与执行》后台测试数据的sql语句可能有误，后台delete语句后面没有from。

**Comment by FancyKings** [comment]
祥祥，这个问题，说来十分的尴尬，这个问题发现并与老师反馈后，当时的解决方法是把说明文档的 from 删了，也就是指导大家在解析的时候不对 from 进行强匹配，具体可参见 [commit](https://github.com/youngsamwei/DongmenDB/commit/ecb3d444e3931036528a4dab7ccf32d09cfc32f2)

你可以在下述文件中看到测试样例的 delect 语句格式 [file](https://github.com/youngsamwei/DongmenDB/blob/mastercpp/src_experiment/exp_01_stmt_parser/exp_01_05_delete_test.cpp#L14)

**Comment by cinocinelli** [comment]
已经当作没有from的语句把测试过了
